from conftest import commit_all, git, write

import pytest

from linewatch import diff

SAMPLE = """\
diff --git a/app.py b/app.py
index 1111111..2222222 100644
--- a/app.py
+++ b/app.py
@@ -1,4 +1,5 @@
 import os
-x = 1
+x = 2
+y = 3

 def f():
diff --git a/logo.png b/logo.png
new file mode 100644
index 0000000..3333333
Binary files /dev/null and b/logo.png differ
diff --git a/old.txt b/old.txt
deleted file mode 100644
index 4444444..0000000
--- a/old.txt
+++ /dev/null
@@ -1 +0,0 @@
-gone
diff --git "a/dir/with space.py" "b/dir/with space.py"
new file mode 100644
--- /dev/null
+++ "b/dir/with space.py"
@@ -0,0 +1,2 @@
+a = 1
+b = 2
"""


def test_parse_diff():
    app, logo, old, spaced = diff.parse_diff(SAMPLE)
    assert app.path == "app.py"
    assert app.added_lines == {2, 3}
    assert [l.tag for l in app.hunks[0].lines] == [" ", "-", "+", "+", " ", " "]
    assert app.hunks[0].lines[-1].new_line == 5
    assert app.changed_count == 3
    assert logo.binary and logo.path == "logo.png"
    assert old.deleted and old.path == "old.txt"
    assert spaced.path == "dir/with space.py"
    assert spaced.added_lines == {1, 2}


def test_filter_files_drops_skipped():
    files = diff.parse_diff(SAMPLE)
    files.append(diff.FileChange("yarn.lock", [diff.Hunk([diff.DiffLine("+", 1, "x")])]))
    files.append(diff.FileChange("dist/app.js", [diff.Hunk([diff.DiffLine("+", 1, "x")])]))
    files.append(diff.FileChange("gen.py", [diff.Hunk([diff.DiffLine("+", 1, "x")])]))
    contents = {"gen.py": "# Code generated by protoc. DO NOT EDIT.\nx = 1\n"}
    changes = diff.Changes("test", files, contents.get)
    kept = diff.filter_files(changes, ["dist/**"])
    assert [f.path for f in kept.files] == ["app.py", "dir/with space.py"]
    assert kept.skipped == ["logo.png", "yarn.lock", "dist/app.js", "gen.py"]


def test_staged_reads_the_index_not_the_worktree(make_repo):
    root = make_repo()
    write(root, "a.py", "one\n")
    commit_all(root)
    write(root, "a.py", "one\nstaged\n")
    git(root, "add", "a.py")
    write(root, "a.py", "one\nstaged\nnot staged\n")
    changes = diff.staged(root)
    (f,) = changes.files
    assert f.added_lines == {2}
    assert changes.read("a.py") == "one\nstaged\n"


def test_uncommitted_includes_untracked_files(make_repo):
    root = make_repo()
    write(root, "a.py", "one\n")
    commit_all(root)
    write(root, "a.py", "one\ntwo\n")
    write(root, "new.py", "x\ny\n")
    write(root, "blob.bin", "\0\1\2")
    write(root, ".gitignore", "ignored.py\n")
    write(root, "ignored.py", "secret\n")
    changes = diff.uncommitted(root)
    by_path = {f.path: f for f in changes.files}
    assert set(by_path) == {"a.py", "new.py", "blob.bin", ".gitignore"}
    assert by_path["a.py"].added_lines == {2}
    assert by_path["new.py"].added_lines == {1, 2}
    assert by_path["blob.bin"].binary
    assert changes.read("new.py") == "x\ny\n"


def test_uncommitted_before_the_first_commit(make_repo):
    root = make_repo()
    write(root, "a.py", "one\n")
    git(root, "add", "a.py")
    changes = diff.uncommitted(root)
    assert [f.path for f in changes.files] == ["a.py"]


def test_parse_range(make_repo):
    root = make_repo()
    write(root, "a.py", "one\n")
    first = commit_all(root)
    write(root, "a.py", "one\ntwo\n")
    commit_all(root)
    write(root, "a.py", "one\ntwo\nthree\n")
    commit_all(root)
    changes = diff.parse_range(root, f"{first}..HEAD~1")
    assert changes.files[0].added_lines == {2}
    assert diff.parse_range(root, first).files[0].added_lines == {2, 3}
    assert changes.read("a.py") == "one\ntwo\n"
    with pytest.raises(diff.GitError, match="unknown commit"):
        diff.parse_range(root, "nope..HEAD")


def push_setup(make_repo):
    root = make_repo()
    remote = root.parent / "remote.git"
    git(root.parent, "init", "-q", "--bare", str(remote))
    git(root, "remote", "add", "origin", str(remote))
    write(root, "a.py", "one\n")
    base = commit_all(root)
    git(root, "push", "-q", "--no-verify", "origin", "main")
    return root, base


def test_pushed_existing_branch(make_repo):
    root, base = push_setup(make_repo)
    write(root, "a.py", "one\ntwo\n")
    head = commit_all(root)
    (changes,) = diff.pushed(root, f"refs/heads/main {head} refs/heads/main {base}\n", "origin")
    assert changes.files[0].added_lines == {2}
    assert changes.description == "commits pushed from main"


def test_pushed_new_branch_reviews_only_new_commits(make_repo):
    root, base = push_setup(make_repo)
    git(root, "switch", "-q", "-c", "feature")
    write(root, "b.py", "new\n")
    head = commit_all(root)
    (changes,) = diff.pushed(root, f"refs/heads/feature {head} refs/heads/feature {diff.ZERO_SHA}\n", "origin")
    assert [f.path for f in changes.files] == ["b.py"]


def test_pushed_first_push_of_a_repo(make_repo):
    root = make_repo()
    write(root, "a.py", "one\n")
    head = commit_all(root)
    (changes,) = diff.pushed(root, f"refs/heads/main {head} refs/heads/main {diff.ZERO_SHA}\n", "origin")
    assert changes.files[0].added_lines == {1}


def test_pushed_skips_deletes_and_already_pushed(make_repo):
    root, base = push_setup(make_repo)
    lines = (
        f"(delete) {diff.ZERO_SHA} refs/heads/old {base}\n"
        f"refs/heads/main {base} refs/heads/copy {diff.ZERO_SHA}\n"
    )
    assert diff.pushed(root, lines, "origin") == []


def test_pushed_unknown_remote_sha_falls_back(make_repo):
    root, base = push_setup(make_repo)
    write(root, "a.py", "one\ntwo\n")
    head = commit_all(root)
    unknown = "1" * 40  # e.g. a force push over commits we never fetched
    (changes,) = diff.pushed(root, f"refs/heads/main {head} refs/heads/main {unknown}\n", "origin")
    assert changes.files[0].added_lines == {2}
