"""Collect the changes to review from git and parse them."""

from __future__ import annotations

import fnmatch
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

# Lines of unchanged code around each change, so the model sees the context.
CONTEXT_LINES = 10

EMPTY_TREE = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"
ZERO_SHA = "0" * 40

# Files that are never reviewed: lockfiles and generated or minified code.
ALWAYS_SKIPPED = [
    "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml",
    "bun.lockb", "poetry.lock", "Pipfile.lock", "uv.lock", "Cargo.lock",
    "Gemfile.lock", "composer.lock", "go.sum", "*.min.js", "*.min.css", "*.map",
    "*.pb.go", "*_pb2.py", "*_pb2_grpc.py",
]
GENERATED_MARKERS = ("@generated", "do not edit", "auto-generated", "autogenerated")


class GitError(Exception):
    """Raised when git can't produce the changes."""


@dataclass
class DiffLine:
    tag: str  # "+" added, "-" removed, " " context
    new_line: int | None  # line number in the new file; None for removed lines
    text: str


@dataclass
class Hunk:
    lines: list[DiffLine] = field(default_factory=list)


@dataclass
class FileChange:
    path: str
    hunks: list[Hunk] = field(default_factory=list)
    binary: bool = False
    deleted: bool = False

    @property
    def added_lines(self) -> set[int]:
        return {l.new_line for h in self.hunks for l in h.lines if l.tag == "+"}

    @property
    def changed_count(self) -> int:
        return sum(1 for h in self.hunks for l in h.lines if l.tag != " ")


@dataclass
class Changes:
    """One set of changes to review, and a way to read the new file contents."""

    description: str
    files: list[FileChange]
    read: Callable[[str], str | None]
    skipped: list[str] = field(default_factory=list)


def git(root: Path, *args: str, check: bool = True) -> str:
    try:
        out = subprocess.run(
            ["git", "-c", "core.quotepath=false", *args],
            cwd=root, capture_output=True, text=True, errors="replace",
        )
    except OSError as exc:
        raise GitError(f"could not run git: {exc}")
    if check and out.returncode != 0:
        raise GitError(f"git {' '.join(args)} failed: {out.stderr.strip()}")
    return out.stdout


def _unquote(path: str) -> str:
    if len(path) >= 2 and path[0] == path[-1] == '"':
        return path[1:-1].encode("latin-1", "backslashreplace").decode("unicode_escape")
    return path


HUNK_HEADER = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@")


def parse_diff(text: str) -> list[FileChange]:
    files: list[FileChange] = []
    current: FileChange | None = None
    new_line = 0
    for raw in text.splitlines():
        if raw.startswith("diff --git "):
            # The real path comes from the +++ line; this is a fallback for
            # binary files and pure renames, which have none.
            match = re.match(r'^diff --git (?:"?a/.*"?) ("?)b/(.*)\1$', raw)
            path = match.group(2) if match else raw.split(" b/", 1)[-1]
            current = FileChange(path=_unquote(path))
            files.append(current)
        elif current is None:
            continue
        elif raw.startswith("deleted file mode"):
            current.deleted = True
        elif raw.startswith("Binary files ") or raw == "GIT binary patch":
            current.binary = True
        elif raw.startswith("+++ "):
            target = _unquote(raw[4:].rstrip("\t"))
            if target != "/dev/null":
                current.path = target[2:] if target.startswith("b/") else target
        elif raw.startswith("--- ") and not current.hunks:
            continue
        elif raw.startswith("@@"):
            match = HUNK_HEADER.match(raw)
            new_line = int(match.group(1)) if match else 0
            current.hunks.append(Hunk())
        elif current.hunks and raw[:1] in ("+", "-", " ", ""):
            # An empty line is a blank context line whose space was stripped.
            tag, body = (raw[0], raw[1:]) if raw else (" ", "")
            if tag == "-":
                current.hunks[-1].lines.append(DiffLine("-", None, body))
            else:
                current.hunks[-1].lines.append(DiffLine(tag, new_line, body))
                new_line += 1
    return files


def _matches(path: str, patterns: list[str]) -> bool:
    name = path.rsplit("/", 1)[-1]
    return any(fnmatch.fnmatch(path, p) or fnmatch.fnmatch(name, p) for p in patterns)


def _looks_generated(content: str | None) -> bool:
    if not content:
        return False
    head = "\n".join(content.splitlines()[:5]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def filter_files(changes: Changes, exclude: list[str]) -> Changes:
    """Drop deleted, binary, excluded and generated files (use case 16)."""
    kept, skipped = [], []
    for f in changes.files:
        if f.deleted or (not f.hunks and not f.binary):
            continue
        if f.binary or _matches(f.path, ALWAYS_SKIPPED + exclude) or _looks_generated(changes.read(f.path)):
            skipped.append(f.path)
            continue
        kept.append(f)
    return Changes(changes.description, kept, changes.read, changes.skipped + skipped)


def _diff_args() -> list[str]:
    return ["diff", "--no-color", "--no-ext-diff", "-M", f"-U{CONTEXT_LINES}"]


def _show(root: Path, spec: str) -> str | None:
    out = subprocess.run(
        ["git", "show", spec], cwd=root, capture_output=True, text=True, errors="replace"
    )
    return out.stdout if out.returncode == 0 else None


def staged(root: Path) -> Changes:
    """What the pre-commit hook reviews: the staged changes."""
    text = git(root, *_diff_args(), "--cached")
    return Changes("staged changes", parse_diff(text), lambda p: _show(root, f":{p}"))


def commit_range(root: Path, base: str, head: str, description: str | None = None) -> Changes:
    text = git(root, *_diff_args(), base, head)
    return Changes(
        description or f"{base[:12]}..{head[:12]}",
        parse_diff(text),
        lambda p: _show(root, f"{head}:{p}"),
    )


def _has_head(root: Path) -> bool:
    return bool(git(root, "rev-parse", "--verify", "-q", "HEAD", check=False).strip())


def uncommitted(root: Path) -> Changes:
    """What `linewatch review` checks by default: everything not committed yet."""
    base = "HEAD" if _has_head(root) else EMPTY_TREE
    files = parse_diff(git(root, *_diff_args(), base))

    def read(path: str) -> str | None:
        try:
            return (root / path).read_text(errors="replace")
        except OSError:
            return None

    untracked = git(root, "ls-files", "--others", "--exclude-standard", "-z").split("\0")
    for path in filter(None, untracked):
        try:
            data = (root / path).read_bytes()
        except OSError:
            continue
        change = FileChange(path=path)
        if b"\0" in data[:8192]:
            change.binary = True
        else:
            lines = data.decode(errors="replace").splitlines()
            change.hunks = [Hunk([DiffLine("+", i, t) for i, t in enumerate(lines, 1)])]
        files.append(change)
    return Changes("uncommitted changes", files, read)


def parse_range(root: Path, spec: str) -> Changes:
    """`A..B`, or a single commit `A` meaning A..HEAD."""
    base, _, head = spec.partition("..")
    head = head or "HEAD"
    for rev in (base, head):
        if not git(root, "rev-parse", "--verify", "-q", f"{rev}^{{commit}}", check=False).strip():
            raise GitError(f"unknown commit {rev!r}")
    return commit_range(root, base, head, spec)


def _exists(root: Path, sha: str) -> bool:
    out = subprocess.run(
        ["git", "cat-file", "-e", f"{sha}^{{commit}}"], cwd=root, capture_output=True
    )
    return out.returncode == 0


def pushed(root: Path, ref_lines: str, remote: str) -> list[Changes]:
    """What the pre-push hook reviews: one range per pushed ref.

    `ref_lines` is what git writes to the hook's stdin:
    `<local ref> <local sha> <remote ref> <remote sha>` per line.
    """
    result = []
    for line in ref_lines.splitlines():
        parts = line.split()
        if len(parts) != 4:
            continue
        local_ref, local_sha, _, remote_sha = parts
        if local_sha == ZERO_SHA:
            continue  # deleting a remote branch
        if remote_sha != ZERO_SHA and _exists(root, remote_sha):
            base = remote_sha
        else:
            base = _new_branch_base(root, local_sha, remote)
            if base is None:
                continue
        name = local_ref.removeprefix("refs/heads/")
        result.append(commit_range(root, base, local_sha, f"commits pushed from {name}"))
    return result


def _new_branch_base(root: Path, local_sha: str, remote: str) -> str | None:
    """For a new branch, start from the parent of the oldest commit the remote lacks."""
    new = git(root, "rev-list", "--reverse", local_sha, "--not", f"--remotes={remote}").split()
    if not new:
        return None
    parent = git(root, "rev-parse", "--verify", "-q", f"{new[0]}^", check=False).strip()
    return parent or EMPTY_TREE
